version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build
after_build:
    - cmd: dotnet publish
artifacts:
 - path: 'bin\Debug\netcoreapp2.0\publish'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
on_finish :
  # any cleanup in here
deploy:
  - provider: Environment
    name: AzureDev1