language: csharp
solution: dot-net-core-travis.csproj
mono: none
dotnet: 2.0.0
dist: trusty
script: 
  - dotnet restore
  - dotnet build
  - dotnet publish
deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true